# Generated by Django 3.2.6 on 2021-08-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bid_winner',
            field=models.CharField(default='Default_Value', max_length=44),
        ),
    ]
