# Generated by Django 3.2.6 on 2021-08-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_close_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='bids',
        ),
        migrations.AddField(
            model_name='listing',
            name='bids',
            field=models.IntegerField(null=True),
        ),
    ]
